package com.proativaservicos.util.constantes;

import org.apache.commons.lang3.EnumUtils;
import org.apache.commons.lang3.StringUtils;

import com.proativaservicos.util.TextUtil;

public enum InstituicaoFinanceiraEnum {

	BANCO_BRASIL("BANCO DO BRASIL S.A", "1"), 
	BRADESCO("BRADESCO S.A", "237"),
	NU_PAGAMENTOS("NU PAGAMENTOS S.A", "260"), 
	PAGSEGURO_INTERNET("Pagseguro Internet S.A", "290"),
	MERCADO_PAGO("Mercado Pago - conta do Mercado Livre", "323"), 
	NEXT_BANK("NEXT BANK", "237"),
	SOFISA("BANCO SOFISA S.A", "637"), 
	INTER("BANCO INTER S.A", "77"), 
	ITAU_UNIBANCO("ITAÚ UNIBANCO S.A", "341"),
	CEF("CAIXA ECONÔMICA FEDERAL", "104"), 
	SANTANDER("BANCO SANTANDER BRASIL S.A", "33"),
	BANCO_ORIGINAL("BANCO ORIGINAL S.A", "212"), BANCOOB_SICOOB("BANCOOB - SICOOB", "756"),
	BANCO_VOTORANTIM("BANCO VOTORANTIM S.A", "655"), NEON_PAGAMENTOS("NEON PAGAMENTOS S.A", "655"),
	BANRISUL("BANCO DO ESTADO R.G. SUL S.A ","41"),
	BANCO_MERCANTIL_DO_BRASIL("BANCO MERCANTIL DO BRASIL S.A", "389"), BANCO_SAFRA("BANCO SAFRA S.A", "422"),
	BANCO_DE_BRASILIA("BANCO DE BRASÍLIA", "70"), UNICRED_COOPERATIVA("UNICRED COOPERATIVA", "136"),
	BANCO_RIBEIRAO_PRETO("BANCO RIBEIRÃO PRETO", "741"), BANCO_CETELEM("BANCO CETELEM S.A", "739"),
	BANCO_SEMEAR("BANCO SEMEAR S.A", "743"), PLANNER_CORRETORA_DE_VALORES("PLANNER CORRETORA DE VALORES S.A", "100"),
	BANCO_B3("BANCO B3 S.A", "96"),
	BANCO_RABOBANK_INTERNACIONAL_DO_BRASIL("Banco RABOBANK INTERNACIONAL DO BRASIL S.A", "747"),
	SICREDI("SICREDI S.A", "748"), BNP_PARIBAS_BRASIL("BNP PARIBAS BRASIL S.A", "752"),
	UNICRED_CENTRAL_RS("UNICRED CENTRAL RS", "91"), KIRTON_BANK("KIRTON BANK", "399"),
	PORTOCRED("PORTOCRED S.A", "108"), BANCO_KEB_HANA_DO_BRASIL("BANCO KEB HANA DO BRASIL S.A", "757"),
	XP_INVESTIMENTOS("XP INVESTIMENTOS S.A", "102"), UNIPRIME_NORTE_DO_PARANA("UNIPRIME NORTE DO PARANÁ", "84"),
	CM_CAPITAL_MARKETS_CCTVM_LTDA("CM CAPITAL MARKETS CCTVM LTDA", "180"),
	BANCO_MORGAN_NLEY("BANCO MORGAN STANLEY S.A", "66"), UBS_BRASIL_CCTVM("UBS BRASIL CCTVM S.A", "15"),
	TREVISO_CC("TREVISO CC S.A", "143"), HIPERCARD_BM("HIPERCARD BM S.A", "62"), SAFRA("BCO. J.SAFRA S.A", "74"),
	UNIPRIME_CENTRAL_CCC_LTDA("UNIPRIME CENTRAL CCC LTDA", "99"), BANCO_ALFA("BANCO ALFA S.A.", "25"),
	BCO_ABN_AMRO("BCO ABN AMRO S.A", "75"), BANCO_CARGILL("BANCO CARGILL S.A", "40"), SERVICOOP("SERVICOOP", "190"),
	BANCO_BRADERD("BANCO BRADESCARD", "63"), NOVA_FUTURA_CTVM_LTDA("NOVA FUTURA CTVM LTDA", "191"),
	GOLDMAN_SACHS_DO_BRASIL_BM("GOLDMAN SACHS DO BRASIL BM S.A", "64"),
	CCC_NOROESTE_BRASILEIRO_LTDA("CCC NOROESTE BRASILEIRO LTDA", "97"),
	CCM_DESP_TRÂNS_SC_E_RS("CCM DESP TRÂNS SC E RS", "16"), BANCO_INBURSA("BANCO INBURSA", "12"),
	BANCO_DA_AMAZONIA("BANCO DA AMAZONIA S.A", "3"), CONFIDENCE_CC("CONFIDENCE CC S.A", "60"),

	BANCO_DO_EDO_DO_PARÁ("BANCO DO ESTADO DO PARÁ S.A", "37"), CASA_CREDITO("CASA CREDITO S.A", "159"),
	ALBATROSS_CCV("ALBATROSS CCV S.A", "172"), COOP_CENTRAL_AILOS("COOP CENTRAL AILOS", "85"),
	CENTRAL_COOPERATIVA_DE_CRÉDITO_NO_EDO_DO_ESPÍRITO_SANTO(
			"CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPIRITO SANTO", "114"),
	BBI("BANCO BBI S.A", "36"), BRADESCO_FINANCIAMENTOS("BANCO BRADESCO FINANCIAMENTOS S.A", "394"),
	NORDESTE_DO_BRASIL("BANCO DO NORDESTE DO BRASIL S.A.", "4"), CCB_BRASIL("BANCO CCB BRASIL S.A", "320"),
	CREDFAZ("CREFAZ SCMEPP LTDA","321"),
	HS_FINANCEIRA("HS FINANCEIRA", "189"), LECCA_CFI("LECCA CFI S.A", "105"), KDB_BRASIL("BANCO KDB BRASIL S.A.", "76"),
	TOPAZIO("BANCO TOPÁZIO S.A", "82"), CCR_DE_OURO("CCR DE OURO", "286"),
	POLOCRED_SCMEPP_LTDA("PÓLOCRED SCMEPP LTDA", "93"), CCR_DE_SAO_MIGUEL_DO_OESTE("CCR DE SÃO MIGUEL DO OESTE", "273"),
	ICAP_DO_BRASIL_CTVM_LTDA("ICAP DO BRASIL CTVM LTDA", "157"), SOCRED("SOCRED S.A", "183"),
	NATIXIS_BRASIL("NATIXIS BRASIL S.A", "14"), CARUANA_SCFI("CARUANA SCFI", "130"),
	CODEPE_CVC("CODEPE CVC S.A", "127"), ORIGINAL_DO_AGRONEGOCIO("BANCO ORIGINAL DO AGRONEGÓCIO S.A", "79"),
	BBN_BANCO_BRASILEIRO_DE_NEGOCIOS("BBN BANCO BRASILEIRO DE NEGOCIOS S.A", "81"),
	NDARD_CHARTERED_BI("STANDARD CHARTERED BI S.A", "118"), CRESOL_CONFEDERACAO("CRESOL CONFEDERAÇÃO", "133"),
	AGIBANK("BANCO AGIBANK S.A", "121"), CHINA_BRASIL("BANCO DA CHINA BRASIL S.A", "83"),
	GET_MONEY_CC_LTDA("GET MONEY CC LTDA", "138"), BCO_BANDEPE("BCO BANDEPE S.A", "24"),
	CONFIDENCE_DE_CAMBIO("BANCO CONFIDENCE DE CÁMBIO S.A", "95"), FINAXIS("BANCO FINAXIS", "94"),
	SENFF("SENFF S.A", "276"), MULTIMONEY_CC_LTDA("MULTIMONEY CC LTDA", "137"), BRK("BRK S.A", "92"),
	BCO_DO_EDO_DE_SERGIPE("BANCO BCO DO ESTADO DE SERGIPE S.A", "47"),
	BEXS_BANCO_DE_CAMBIO("BEXS BANCO DE CAMBIO S.A.", "144"), BR_PARTNERS_BI("BR PARTNERS BI", "126"),
	BPP_INSTITUICAO_DE_PAGAMENTOS("BPP INSTITUIÇÃO DE PAGAMENTOS S.A", "301"),
	BRL_TRUST_DTVM_SA("BRL TRUST DTVM SA", "173"), WESTERN_UNION("BANCO WESTERN UNION", "119"),
	PARANA_BANCO("PARANA BANCO S.A", "254"), BARIGUI_CH("BARIGUI CH", "268"), BOCOM_BBM("BANCO BOCOM BBM S.A", "107"),
	CAPITAL("BANCO CAPITAL S.A", "412"), WOORI_BANK_DO_BRASIL("BANCO WOORI BANK DO BRASIL S.A", "124"),
	FACTA_CFI("FACTA S.A. CFI", "149"), STONE_PAGAMENTOS("STONE PAGAMENTOS S.A", "197"),
	BROKER_BRASIL_CC_LTDA("BROKER BRASIL CC LTDA", "142"),

	ITAU("BANCO ITAÚ BBA S.A", "184"), TRIANGULO("BANCO TRIANGULO S.A", "634"), SENSO_CCVM("SENSO CCVM S.A", "545"),
	ICBC_DO_BRASIL_BM("ICBC DO BRASIL BM S.A", "132"), VIPS_CC_LTDA("VIPS CC LTDA", "298"),
	UBS_BRASIL_BI("UBS BRASIL BI S.A", "129"), MS_BANK_BANCO_DE_CAMBIO("MS BANK S.A BANCO DE CÁMBIO", "128"),
	PARMETAL_DTVM_LTDA("PARMETAL DTVM LTDA", "194"), VORTX_DTVM_LTDA("VORTX DTVM LTDA", "310"),
	COMMERZBANK_BRASIL_BANCO_MULTIPLO("COMMERZBANK BRASIL S.A BANCO MÚLTIPLO", "163"), AVI("AVISTA S.A", "280"),
	GUITTA_CC_LTDA("GUITTA CC LTDA", "146"), CCR_DE_PRIMAVERA_DO_LESTE("CCR DE PRIMAVERA DO LESTE", "279"),
	DACASA_FINANCEIRA("DACASA FINANCEIRA S/A", "182"), GENIAL_INVESTIMENTOS_CVM("GENIAL INVESTIMENTOS CVM S.A", "278"),
	IB_CCTVM_LTDA("IB CCTVM LTDA", "271"), BANESTES("BANCO BANESTES S.A", "21"),
	ABC_BRASIL("BANCO ABC BRASIL S.A", "246"), SCOTIABANK_BRASIL("SCOTIABANK BRASIL", "751"),
	BTG_PACTUAL("BANCO BTG PACTUAL S.A", "208"), ODAL("BANCO MODAL S.A", "746"), CLASSICO("BANCO CLASSICO S.A", "241"),
	GUANABARA("BANCO GUANABARA S.A", "612"), INDUSTRIAL_DO_BRASIL("BANCO INDUSTRIAL DO BRASIL S.A", "604"),
	CREDIT_SUISSE("BANCO CREDIT SUISSE (BRL) S.A", "505"), FAIR_CC("BANCO FAIR CC S.A", "196"),
	LA_NACION_ARGENTINA("BANCO LA NACION ARGENTINA", "300"), CITIBANK("CITIBANK N.A", "477"),
	CEDULA("BANCO CEDULA S.A", "266"), BRADESCO_BERJ("BANCO BRADESCO BERJ S.A", "122"),
	MORGAN("BANCO J.P. MORGAN S.A", "376"), BANCO_CAIXA_GERAL_BRASIL("BANCO CAIXA GERAL BRASIL S.A", "473"),
	BANCO_CITIBANK("BANCO CITIBANK S.A", "745"), BANCO_RODOBENS("BANCO RODOBENS S.A", "120"),
	BANCO_FATOR("BANCO FATOR S.A", "265"), BNDES("BNDES", "7"), ATIVA_INVESTIMENTOS("ATIVA S.A INVESTIMENTOS", "188"),
	BGC_LIQUIDEZ_DTVM_LTDA("BGC LIQUIDEZ DTVM LTDA", "134"), BANCO_ALVORADA("BANCO ALVORADA S.A", "641"),
	BANCO_ITAU_CONSIGNADO("BANCO ITAÚ CONSIGNADO S.A", "29"), BANCO_MASTER("BANCO MASTER S.A", "243"),
	HAITONG_BI_DO_BRASIL("HAITONG BI DO BRASIL S.A", "78"),
	BANCO_OLIVEIRA_TRUST_DTVM("BANCO OLIVEIRA TRUST DTVM S.A", "111"), BNY_MELLON_BANCO("BNY MELLON BANCO S.A", "17"),
	PERNAMBUCANAS_FINANC("PERNAMBUCANAS FINANC S.A", "174"),
	LA_PROVINCIA_BUENOIRES_BANCO("LA PROVINCIA BUENOS AIRES BANCO", "495"),
	BRASIL_PLURAL__BANCO("BRASIL PLURAL S.A BANCO", "125"), JPMORGAN_CHASE_BANK("JPMORGAN CHASE BANK", "488"),
	BANCO_ANDBANK("BANCO ANDBANK S.A", "65"), ING_BANK("ING BANK N.V", "492"), BANCO_BCV("BANCO BCV", "250"),
	LEVYCAM_CCV_LTDA("LEVYCAM CCV LTDA", "145"), BANCO_REP_ORIENTAL_URUGUAY("BANCO REP ORIENTAL URUGUAY", "494"),
	BEXS_CC("BEXS CC S.A", "253"), HSBC_BANCO_DE_INVESTIMENTO("HSBC BANCO DE INVESTIMENTO", "269"),
	BCO_ARBI("BCO ARBI S.A", "213"), INTESA_SANPAOLO_BRASIL("INTESA SANPAOLO BRASIL S.A", "139"),
	TRICURY("BANCO TRICURY S.A", "18"), INTERCAP("BANCO INTERCAP S.A", "630"), FIBRA("BANCO FIBRA S.A", "224"),
	LUSO_BRASILEIRO("BANCO LUSO BRASILEIRO S.A", "600"), 
	PAN("BANCO PAN S/A", "623"),
	BRADESCO_CARTOES("BANCO BRADESCO CARTOES S.A", "204"), ITAUBANK("BANCO ITAUBANK S.A", "479"),
	MUFG_BRASIL("BANCO MUFG BRASIL S.A", "456"), SUMITOMO_MITSUI_BRASIL("BANCO SUMITOMO MITSUI BRASIL S.A", "464"),
	OMNI_BANCO("OMNI BANCO S.A", "613"), ITAU_UNIBANCO_HOLDING_BM("ITAÚ UNIBANCO HOLDING BM S.A", "652"),
	INDUL("BANCO INDUSVAL S.A", "653"), CREFISA("BANCO CREFISA S.A", "69"), MIZUHO("BANCO MIZUHO S.A", "370"),
	INVESTCRED_UNIBANCO("BANCO INVESTCRED UNIBANCO S.A", "249"), BMG("BANCO BMG S.A", "318"),
	FICSA("BANCO FICSA S.A", "626"), SAGITUR_CC_LTDA("SAGITUR CC LTDA", "270"),
	SOCIETE_GENERALE_BRASIL("BANCO SOCIETE GENERALE BRASIL", "366"), MAGLIANO("MAGLIANO S.A", "113"),
	TULLETT_PREBON_BRASIL_CVC_LTDA("TULLETT PREBON BRASIL CVC LTDA", "131"),
	CREDIT_SUISSE_HEDGING("C.SUISSE HEDGING-GRIFFO CV S.A (Credit Suisse)", "11"), BANCO_PAULI("BANCO PAULISTA", "611"),
	BOFA_MERRILL_LYNCH_BM("BOFA MERRILL LYNCH BM S.A", "755"), CCR_REG_MOGIANA("CCR REG MOGIANA", "89"),
	PINE("BANCO PINE S.A", "643"), EASYNVEST("EASYNVEST - T�TULO CV S.A", "140"), DAYCOVAL("BANCO DAYCOVAL S.A", "707"),
	CAROL_DTVM_LTDA("CAROL DTVM LTDA", "288"), RENASCENCA_DTVM_LTDA("RENASCENCA DTVM LTDA", "101"),
	DEUTSCHE_BANK("DEUTSCHE BANK S.A BANCO ALEMÃO", "487"), CIFRA("BANCO CIFRA", "233"), GUIDE("GUIDE", "177"),
	RENDIMENTO("BANCO RENDIMENTO S.A", "633"), BS2("BANCO BS2 S.A", "218"),
	BS2_DISTRIBUIDORA("BS2 DISTRIBUIDORA DE TÍTULOS E INVESTIMENTOS", "292"),
	OLE("BANCO OLÉ BONSUCESSO CONSIGNADO S.A", "169"), LASTRO_RDV_DTVM_LTDA("LASTRO RDV DTVM LTDA", "293"),
	FRENTE_CC_LTDA("FRENTE CC LTDA", "285"), BT_CC_LTDA("B&T CC LTDA", "80"),
	NOVO_BANCO_CONTINENTAL("NOVO BANCO CONTINENTAL S.A BM", "753"),
	CREDIT_AGRICOL("BANCO CRÉDITO AGRICOLE BR S.A", "222"), SISTEMA("BANCO SISTEMA", "754"),
	CREDIALIANCA("CREDIALIANÇA CCR", "98"), VR("BANCO VR S.A", "610"), OURINVEST("BANCO OURINVEST S.A", "712"),
	CREDICOAMO("CREDICOAMO", "10"), RB_CAPITAL_INVESTIMENTOS("RB CAPITAL INVESTIMENTOS DTVM LTDA", "283"),
	BANCO_JOHN_DEERE("BANCO JOHN DEERE S.A", "217"), ADVANCED_CC_LTDA("ADVANCED CC LTDA", "117"),
	C6_BANK("BANCO C6 S.A - C6 BANK", "336"),
	RENNER("BANCO A.J. RENNER S.A", "654"),
	PICPAY("PicPay", "380");

	public String constante;

	public String numeroBanco;

	private InstituicaoFinanceiraEnum(String chave, String numeroBanco) {

		constante = chave;
		this.numeroBanco = numeroBanco;

	}

	public String getNumeroBanco() {
		return numeroBanco;
	}

	public String getConstante() {

		return constante;
	}

	public static InstituicaoFinanceiraEnum getBanco(String codBanco) {

		for (InstituicaoFinanceiraEnum bancos : InstituicaoFinanceiraEnum.values()) {

			if (bancos.numeroBanco.equalsIgnoreCase(codBanco)) {

				return bancos;
			}

		}

		return null;
	}

	public static InstituicaoFinanceiraEnum retornarEnum(String descricao) {

		if (StringUtils.isNotBlank(descricao)) {

			InstituicaoFinanceiraEnum instituicaoFinanceiraEnum = (InstituicaoFinanceiraEnum) EnumUtils.getEnum(InstituicaoFinanceiraEnum.class, descricao);

			if (instituicaoFinanceiraEnum != null) {

				return instituicaoFinanceiraEnum;
			}

			String descricaoSemAcento = TextUtil.builder(descricao.toUpperCase()).removerAcento().getTexto();

			if (StringUtils.isNotBlank(descricaoSemAcento)) {

				for (InstituicaoFinanceiraEnum banco : values()) {

					if (StringUtils.isNotBlank(banco.getNumeroBanco()) &&

							TextUtil.builder(banco.getNumeroBanco() + " - " + banco.getConstante()).removerAcento()
									.getTexto().trim().contains(descricaoSemAcento)) {

						return banco;
					}

					if (StringUtils.isNotBlank(banco.getNumeroBanco()) && TextUtil.builder(banco.getConstante())
							.removerSA().getTexto().trim().contains(descricaoSemAcento)) {

						return banco;
					}
					
			
					
			//	System.out.println(TextUtil.builder(descricao).removerAcento().removerSA().getTexto()+" - "+TextUtil.builder(banco.constante.toUpperCase()).removerAcento().getTexto());
					
					
					
				}
			}

		}

		return null;
	}

	public static InstituicaoFinanceiraEnum retornarEnumPorCodigoBanco(String codigo) {

		if (org.apache.commons.lang3.StringUtils.isNotBlank(codigo)) {

			for (InstituicaoFinanceiraEnum banco : values()) {

				if (StringUtils.isNotBlank(banco.getNumeroBanco())

						&& banco.getNumeroBanco().equalsIgnoreCase(StringUtils.leftPad(codigo.trim(), 3, "0"))) {

					return banco;
				}
			}
		}

		return null;
	}

	public static void main(String[] args) {
		
		System.out.println(retornarEnum("41").getConstante());


	}
}