/**
 * ProdutoSeguroWebService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.proativaservicos.service.asynchronous.produtoseguros;

public interface ProdutoSeguroWebService extends java.rmi.Remote {
    public com.proativaservicos.service.asynchronous.produtoseguros.OcorrenciaProdutoSeguroReturn atualizarProdutoSeguro(com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.OcorrenciaProdutoSeguroReturn cancelarProdutoSeguro(com.proativaservicos.service.asynchronous.produtoseguros.CancelamentoProdutoSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.OcorrenciaProdutoSeguroReturn cancelarProdutoSeguroApi(com.proativaservicos.service.asynchronous.produtoseguros.CancelamentoProdutoSeguroApiParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ConsigBusinessException;
    public com.proativaservicos.service.asynchronous.produtoseguros.CancelamentoSeguroReturn cancelarSeguro(com.proativaservicos.service.asynchronous.produtoseguros.DadosCancelamentoSegurosParameter parameter) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.GravaPropostaSeguroReturn gravaPropostaSeguro(com.proativaservicos.service.asynchronous.produtoseguros.PropostaSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.GravaPropostaSeguroReturn gravarPropostaDigToken(com.proativaservicos.service.asynchronous.produtoseguros.PropostaSeguroParameterDigToken param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.GravaPropostaSeguroReturn gravaPropostaSeguroUpgrade(com.proativaservicos.service.asynchronous.produtoseguros.PropostaSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaPlanosSeguroReturn listaPlanos(com.proativaservicos.service.asynchronous.produtoseguros.PlanosSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaPlanosSeguroReturn listaPlanosRating(com.proativaservicos.service.asynchronous.produtoseguros.PlanosSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaPlanosSeguroReturn listaPlanosUpgrade(com.proativaservicos.service.asynchronous.produtoseguros.PlanosSeguroUpgradeParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ScriptAdesaoReturn gerarScriptUpgrade(com.proativaservicos.service.asynchronous.produtoseguros.ScriptSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ScriptAdesaoReturn geraScript(com.proativaservicos.service.asynchronous.produtoseguros.ScriptSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ScriptAdesaoReturn gerarScriptVendaUpgrade(com.proativaservicos.service.asynchronous.produtoseguros.ScriptSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ScriptAdesaoReturn geraScriptVenda(com.proativaservicos.service.asynchronous.produtoseguros.ScriptSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaFormaPagamentoSeguroReturn listaFormaPagamentoProdutoSeguro(com.proativaservicos.service.asynchronous.produtoseguros.FormaPagamentoSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaTipoBeneficiosReturn listaTipoBeneficio(com.proativaservicos.service.asynchronous.produtoseguros.TipoBeneficioParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ObtemFormaEnvioReturn obtemFormasDeEnvio(com.proativaservicos.service.asynchronous.produtoseguros.ObtemFormaEnvioProdutoSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException;
    public com.proativaservicos.service.asynchronous.produtoseguros.InclusaoTelefonesComplementaresReturn incluirTelefonesComplementares(com.proativaservicos.service.asynchronous.produtoseguros.InclusaoTelefonesComplementaresParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ConsistenciasSegurosReturn obterConsistenciasSeguros(com.proativaservicos.service.asynchronous.produtoseguros.ConsistenciaSegurosParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ValidacaoElegibilidadeReturn validarElegibilidadeSeguros(com.proativaservicos.service.asynchronous.produtoseguros.ValidacaoElegibilidadeParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ValidacaoElegibilidadeUpgradeReturn validarElegibilidadeSegurosUpgrade(com.proativaservicos.service.asynchronous.produtoseguros.ValidacaoElegibilidadeUpgradeParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ConsistenciaTelefonesComplementaresReturn consultarConsistenciaTelefonesComplementares(com.proativaservicos.service.asynchronous.produtoseguros.ConsistenciaTelefonesComplementaresParameter param) throws java.rmi.RemoteException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaCartoesSeguroReturn obterCartoesDisponiveis(com.proativaservicos.service.asynchronous.produtoseguros.ListaCartoesSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.CalculoSeguroReturn calcularSeguro(com.proativaservicos.service.asynchronous.produtoseguros.CalculoSeguroParameter param) throws java.rmi.RemoteException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ObterStatusSeguroReturn obterStatusSeguro(com.proativaservicos.service.asynchronous.produtoseguros.ObterStatusSeguroParameter param) throws java.rmi.RemoteException;
    public com.proativaservicos.service.asynchronous.produtoseguros.TipoPagamentoSegurosReturn obterTiposPagamentoSeguros(com.proativaservicos.service.asynchronous.produtoseguros.TipoPagamentoParameter tipoPagamentoParameter) throws java.rmi.RemoteException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaPlanosSeguroLimiteSaqueReturn obterPlanosLimiteSaque(com.proativaservicos.service.asynchronous.produtoseguros.PlanosSeguroLimiteSaqueParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.CartaoClienteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ConsigBusinessException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaPlanosSeguroLimiteSaqueReturn obterPlanosLimiteSaqueDigToken(com.proativaservicos.service.asynchronous.produtoseguros.PlanosSeguroLimiteSaqueDigTokenParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.CartaoClienteException, com.proativaservicos.service.asynchronous.produtoseguros.ServiceException, com.proativaservicos.service.asynchronous.produtoseguros.ConsigBusinessException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ListaCartoesSeguroReturn obterCartoesUpgrade(com.proativaservicos.service.asynchronous.produtoseguros.ListaCartoesSeguroParameter param) throws java.rmi.RemoteException, com.proativaservicos.service.asynchronous.produtoseguros.ProdutoSeguroException;
    public com.proativaservicos.service.asynchronous.produtoseguros.ObterStatusCompletoPropostaSeguroReturn obterStatusCompletoPropostaSeguro(com.proativaservicos.service.asynchronous.produtoseguros.ObterStatusSeguroParameter param) throws java.rmi.RemoteException;
}
