import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.proativaservicos.model.IntegracaoWs;
import com.proativaservicos.model.bancoMaster.ConvenioResponse;
import com.proativaservicos.util.JsonUtil;
import localhost.TestePassando;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class TestesJson {


    public static void main(String[] args) throws JsonProcessingException {

        String json = "[\n" +
                "    {\n" +
                "        \"cdCpf\": \"4263692705\",\n" +
                "        \"idConvenio\": \"235\"\n" +
                "    },\n" +
                "    {\n" +
                "        \"cdCpf\": \"4263692705\",\n" +
                "        \"idConvenio\": \"76\"\n" +
                "    }\n" +
                "]";

        //    SkillsResponse skillsResponse = JsonUtil.fromJson(json, SkillsResponse.class);
        //   System.out.println(skillsResponse);

        if (JsonUtil.isJSON(json)) {

            ConvenioResponse convenioResponse = JsonUtil.fromJson(json, ConvenioResponse.class);
            System.out.println(convenioResponse);

        } else if (JsonUtil.isArrayJSON(json)) {
            System.out.println("é um array");
            ObjectMapper mapper = new ObjectMapper();
            List<ConvenioResponse> skills = JsonUtil.fromJsonArray(json, ConvenioResponse.class);

            skills.forEach(System.out::println);
        }

        IntegracaoWs ab = new IntegracaoWs();


        ab.setUrl("http://localhost:8080/integracao-ws/integracao-ws");
        TestePassando testePassando = new TestePassando();
testePassando.teste(ab);
        System.out.println("TOKEN: " + ab.getToken());
        System.out.println("URL: " + ab.getUrl());
        ab.setToken("ALTEROU::::");

        testePassando.teste(ab);
        System.out.println(ab.getToken());
        System.out.println(getHorarioAtual());

        String ht = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n" +
                "<HTML>\n" +
                "\n" +
                "<HEAD>\n" +
                "    <META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n" +
                "    <TITLE>ERROR: The request could not be satisfied</TITLE>\n" +
                "</HEAD>\n" +
                "\n" +
                "<BODY>\n" +
                "    <H1>403 ERROR</H1>\n" +
                "    <H2>The request could not be satisfied.</H2>\n" +
                "    <HR noshade size=\"1px\">\n" +
                "    Request blocked.\n" +
                "    We can't connect to the server for this app or website at this time. There might be too much traffic or a\n" +
                "    configuration error. Try again later, or contact the app or website owner.\n" +
                "    <BR clear=\"all\">\n" +
                "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n" +
                "    <BR clear=\"all\">\n" +
                "    <HR noshade size=\"1px\">\n" +
                "    <PRE>\n" +
                "Generated by cloudfront (CloudFront)\n" +
                "Request ID: QtlQmHA7gMqiO8pn_m3njpzImXOKFg-gacTI-dEnWu81XVuA0Nbs4Q==\n" +
                "</PRE>\n" +
                "    <ADDRESS>\n" +
                "    </ADDRESS>\n" +
                "</BODY>\n" +
                "\n" +
                "</HTML>";


   //     System.out.println("CONTEM: "+ht.contains("403 ERROR"));

        String  teste  ="✅ - Operador não está logado. ";
        System.out.println(teste.contains("✅ "));

    }
    public static String getHorarioAtual() {
        long agora = System.currentTimeMillis();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        return sdf.format(new Date(agora));
    }


}
