package com.proativaservicos.util;

import java.io.Serializable;
import java.text.Normalizer;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.text.StrSubstitutor;


@SuppressWarnings("deprecation")
public class TextUtil implements Serializable {

	private static final long serialVersionUID = 1L;
	private String texto;
	private String texto1;
	private String texto2;

	private TextUtil(String texto) {
		this.texto = texto;
	}

	private TextUtil(String texto1, String texto2) {
		this.texto1 = texto1;
		this.texto2 = texto2;
	}

	public String getTexto() {
		return this.texto;
	}

	public static TextUtil builder(String texto) {
		return new TextUtil(texto);
	}

	public static TextUtil builder(String texto1, String texto2) {
		return new TextUtil(texto1, texto2);
	}

	public TextUtil coalesce() {
		this.texto = (this.texto1 != null) ? this.texto1 : this.texto2;

		return this;
	}

	public TextUtil substituirVariavelTexto(Map<String, String> variaveis) {
		this.texto = StrSubstitutor.replace(this.texto, variaveis, "%", "%");

		return this;
	}

	public TextUtil removerAcento() {
		this.texto = (this.texto == null) ? null
				: Normalizer.normalize(this.texto, Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "");

		return this;
	}
	
	public TextUtil removerSA() {
		
		this.texto = (this.texto==null)?null:StringUtils.removeEnd(this.texto, "SA");
		
		this.texto = (this.texto == null) ? null
				: Normalizer.normalize(this.texto, Normalizer.Form.NFD).replaceAll("S/A", "");
		
		this.texto = (this.texto == null) ? null
				: Normalizer.normalize(this.texto, Normalizer.Form.NFD).replaceAll("S.A.", "");

		this.texto = (this.texto == null) ? null
				: Normalizer.normalize(this.texto, Normalizer.Form.NFD).replaceAll("S.A", "");
		
		if(this.texto!=null)
		this.texto = StringUtils.trimToEmpty(StringUtils.removeStartIgnoreCase(texto, "BANCO"));
		
		return this;
	}

	public  TextUtil removerTagsHtml() {
		if (this.texto == null) return null;

		// Remove entidades HTML como &#x3D; ou &nbsp;
		String semEntidades = this.texto.replaceAll("&[^;]+;", " ");

		// Remove todas as tags HTML
		String semTags = semEntidades.replaceAll("<[^>]*>", " ");

		// Remove espaços duplicados e quebra de linha
		this.texto = semTags.replaceAll("\\s+", " ").trim();
		return this;
	}

	public static void main(String[] args) {
		String html = "[Saque: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n" +
				"<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n" +
				"<TITLE>ERROR: The request could not be satisfied</TITLE>\n" +
				"</HEAD><BODY>\n" +
				"<H1>504 Gateway Timeout ERROR</H1>\n" +
				"<H2>The request could not be satisfied.</H2>\n" +
				"<HR noshade size=\"1px\">\n" +
				"We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n" +
				"<BR clear=\"all\">\n" +
				"If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n" +
				"<BR clear=\"all\">\n" +
				"<HR noshade size=\"1px\">\n" +
				"<PRE>\n" +
				"Generated by cloudfront (CloudFront) HTTP3 Server\n" +
				"Request ID: Pwze-by_iN7l5p4p3gCc8UDwe3XdELfz8f0M1vlXjr_SG2LNGLjGfA&#x3D;&#x3D;\n" +
				"</PRE>\n" +
				"<ADDRESS>\n" +
				"</ADDRESS>\n" +
				"</BODY></HTML> ]";
		System.out.println( TextUtil.builder("TESTEW 132").removerTagsHtml().getTexto());
	}

}
